### ISSUE TITLE
Issue with forecasts.yaml

### ISSUE THREAD

**Issue by stuckinthe** [Eugeniusz-Gienek/kodi_weather_ha#1]
I followed your directions but when I restart HA. I get the following error. Running on Arch Aarch64

`Apr 19 14:49:41 alarm systemd[1]: Started Home assistant.
Apr 19 14:49:42 alarm hass[611278]: 2024-04-19 14:49:42.236 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] while parsing a block collection
Apr 19 14:49:42 alarm hass[611278]:   in "/var/lib/hass/forecasts.yaml", line 1, column 1
Apr 19 14:49:42 alarm hass[611278]: expected <block end>, but found '<block sequence start>'
Apr 19 14:49:42 alarm hass[611278]:   in "/var/lib/hass/forecasts.yaml", line 131, column 3
Apr 19 14:49:42 alarm hass[611278]: 2024-04-19 14:49:42.236 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: while parsing a block collection
Apr 19 14:49:42 alarm hass[611278]:   in "forecasts.yaml", line 1, column 1
Apr 19 14:49:42 alarm hass[611278]: expected <block end>, but found '<block sequence start>'
Apr 19 14:49:42 alarm hass[611278]:   in "forecasts.yaml", line 131, column 3. Activating recovery mode
Apr 19 14:49:43 alarm hass[611278]: 2024-04-19 14:49:43.567 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.11.8 is deprecated and will be removed in Home Assistant 2024.4; Please upgrade Python to 3.12`

**Comment by Eugeniusz-Gienek** [comment]
Can You please double check that the YAML indents are correct? I have uploaded the [file](https://github.com/Eugeniusz-Gienek/kodi_weather_ha/blob/main/forecasts.example.yaml) which I am using - can You please compare?

**Comment by Eugeniusz-Gienek** [comment]
Additionally, I do this in the configuration.yaml:
`template: !include forecasts.yaml`

I'd recommend also checking if You maybe have already another `template: smth` entry in the configuration.yaml file

**Comment by stuckinthe** [comment]
The problem was with the indentations.

I am running into a new problem.

```
2024-04-19 18:55:59.760 T:632067   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'timedelta' is not defined
                                                   Traceback (most recent call last):
                                                     File "/home/alarm/.kodi/addons/weather.ha/default.py", line 8, in <module>
                                                       ha_weather.MAIN(mode=sys.argv[1],w=WINDOW)
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/ha_weather.py", line 73, in __init__
                                                       self.getForecasts()
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/ha_weather.py", line 178, in getForecasts
                                                       set_property('Day'+count+'.Title'      , convert_datetime(parse_date(forecast['day'+count+'_date']),'>
                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/util.py", line 60, in parse_date
                                                       datetime_obj = utc_to_local(datetime_obj)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/util.py", line 55, in utc_to_local
                                                       assert utc_dt.resolution >= timedelta(microseconds=1)
                                                                                   ^^^^^^^^^
                                                   NameError: name 'timedelta' is not defined
                                                   -->End of Python script error report<--
```

**Comment by Eugeniusz-Gienek** [comment]
That's kinda weird. Thanks for pointing this out. Anyways, I've fixed it - it's in the repo.
If You don't want to download the whole archive once more - just edit the file `lib/util.py` - row 55, from this:
`     assert utc_dt.resolution >= timedelta(microseconds=1)`
to this:
`     assert utc_dt.resolution >= datetime.timedelta(microseconds=1)`

**Comment by stuckinthe** [comment]
```
2024-04-19 19:23:00.970 T:634456   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: type object 'datetime.datetime' has no attribute 'timedelta'
                                                   Traceback (most recent call last):
                                                     File "/home/alarm/.kodi/addons/weather.ha/default.py", line 8, in <module>
                                                       ha_weather.MAIN(mode=sys.argv[1],w=WINDOW)
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/ha_weather.py", line 73, in __init__
                                                       self.getForecasts()
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/ha_weather.py", line 178, in getForecasts
                                                       set_property('Day'+count+'.Title'      , convert_datetime(parse_date(forecast['day'+count+'_date']),'>
                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/util.py", line 60, in parse_date
                                                       datetime_obj = utc_to_local(datetime_obj)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/util.py", line 55, in utc_to_local
                                                       assert utc_dt.resolution >= datetime.timedelta(microseconds=1)
                                                                                   ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
                                                   -->End of Python script error report<--
```

**Comment by Eugeniusz-Gienek** [comment]
Okay, can You please re-use the new `lib/util.py` file from the repo?

**Comment by Eugeniusz-Gienek** [comment]
I am actually surprised this happens as on my side no errors at all.... However, Kodi is running on Debian, not Arch - that might explain the differences.

**Comment by stuckinthe** [comment]
```
          - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: time data '04/19/2024' does not match format '%d.%m.%Y'
                                                   Traceback (most recent call last):
                                                     File "/home/alarm/.kodi/addons/weather.ha/default.py", line 8, in <module>
                                                       ha_weather.MAIN(mode=sys.argv[1],w=WINDOW)
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/ha_weather.py", line 73, in __init__
                                                       self.getForecasts()
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/ha_weather.py", line 178, in getForecasts
                                                       set_property('Day'+count+'.Title'      , convert_datetime(parse_date(forecast['day'+count+'_date']),'>
                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
                                                     File "/home/alarm/.kodi/addons/weather.ha/lib/conversions.py", line 235, in convert_datetime
                                                       timestruct = time.strptime(stamp, "%d.%m.%Y")
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/_strptime.py", line 561, in _strptime_time
                                                       tt = _strptime(data_string, format)[0]
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
                                                       raise ValueError("time data %r does not match format %r" %
                                                   ValueError: time data '04/19/2024' does not match format '%d.%m.%Y'
                                                   -->End of Python script error report<--
```

Also it reports my current temp as 171F when it should be 72F.

**Comment by Eugeniusz-Gienek** [comment]
Ah, I see what is going on. Metric vs non-metric system. I didn't take it into consideration xD
Okay, I'll fix that tomorrow - it's almost 3 am here so I don't want to accidentally mess up the code.

**Comment by Eugeniusz-Gienek** [comment]
I've pushed a fix. Can You please re-install the plugin? The settings data can be kept I assume.

**Comment by stuckinthe** [comment]
Thanks. It works now without errors and it displays the proper temperature.

**Comment by stuckinthe** [comment]
Thanks. It works now without errors and it displays the proper temperature.

**Comment by Eugeniusz-Gienek** [comment]
Yay, I am really happy that worked :) Enjoy!
