### ISSUE TITLE
Wrong wind speed

### ISSUE THREAD

**Issue by Theetjuh** [Eugeniusz-Gienek/kodi_weather_ha#6]
Hi,

First of all, thanks for this nice addon, especially now Yahoo! has abandoned its service.

I got it all working except I see the wind speed is 3,6x higher then the value in HA.
I have set the unit of measurement to ‘km/h’ like weather.forecast_home is showing.
Within Kodi the speed setting is also set to ‘km/h’, so it should’t need to convert anything.

Thanks in advance for the help!

**Comment by Eugeniusz-Gienek** [comment]
Thanks for mentioning, I'll take a look. Currently I am working on a slightly adjusted version of this, a lot of issues are expected to be fixed there - this included.

**Comment by Eugeniusz-Gienek** [comment]
Seem to work properly now - thanks to @Galaxy102 for support!

**Comment by Theetjuh** [comment]
Version 0.0.6.1 isn’t working for me, I see the following in the logging:
`2024-12-31 17:17:35.150 T:11247   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.9/datetime.py)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/weather.ha/default.py", line 1, in <module>
                                                       from plugin import KodiHomeAssistantWeatherPlugin
                                                     File "/home/osmc/.kodi/addons/weather.ha/plugin/__init__.py", line 1, in <module>
                                                       from ._plugin import KodiHomeAssistantWeatherPlugin
                                                     File "/home/osmc/.kodi/addons/weather.ha/plugin/_plugin.py", line 4, in <module>
                                                       from lib.kodi import KodiLogLevel
                                                     File "/home/osmc/.kodi/addons/weather.ha/lib/kodi/__init__.py", line 1, in <module>
                                                       from ._adapter import KodiWeatherPluginAdapter
                                                     File "/home/osmc/.kodi/addons/weather.ha/lib/kodi/_adapter.py", line 3, in <module>
                                                       from datetime import datetime, UTC
                                                   ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.9/datetime.py)
                                                   -->End of Python script error report<--`
