### ISSUE TITLE
`datetime.UTC` not importable in OSMC

### ISSUE THREAD

**Issue by Galaxy102** [Eugeniusz-Gienek/kodi_weather_ha#8]
Version 0.0.6.1 isn’t working for me, I see the following in the logging:

```2024-12-31 17:17:35.150 T:11247   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.9/datetime.py)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/weather.ha/default.py", line 1, in <module>
                                                       from plugin import KodiHomeAssistantWeatherPlugin
                                                     File "/home/osmc/.kodi/addons/weather.ha/plugin/__init__.py", line 1, in <module>
                                                       from ._plugin import KodiHomeAssistantWeatherPlugin
                                                     File "/home/osmc/.kodi/addons/weather.ha/plugin/_plugin.py", line 4, in <module>
                                                       from lib.kodi import KodiLogLevel
                                                     File "/home/osmc/.kodi/addons/weather.ha/lib/kodi/__init__.py", line 1, in <module>
                                                       from ._adapter import KodiWeatherPluginAdapter
                                                     File "/home/osmc/.kodi/addons/weather.ha/lib/kodi/_adapter.py", line 3, in <module>
                                                       from datetime import datetime, UTC
                                                   ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.9/datetime.py)
                                                   -->End of Python script error report<--
```

_Originally posted by @Theetjuh in https://github.com/Eugeniusz-Gienek/kodi_weather_ha/issues/6#issuecomment-2566574542_

**Comment by Galaxy102** [comment]
Hello @Theetjuh, can you please provide details on which version of OSMC/Kodi you are using?

**Comment by Galaxy102** [comment]
My bad, I wrote the Code with Python 3.12 as interpreter, but current Kodi versions only seem to provide Python 3.8 [1].
I will run checks with Python 3.8 and will provide backwards compatibility next year™ (joking: You can expect a fix soon)


[1]: https://kodi.wiki/index.php?title=Python_libraries&oldid=241224

**Comment by Theetjuh** [comment]
Take your time m8, I rerolled back to version 0.0.5 and that one works great ;)

Version of OSMC and Kodi are the latest, here a snip from the log:

```
2024-12-31 17:21:02.272 T:11482    info <general>: Starting Kodi (21.1). Platform: Linux ARM 32-bit (version for Vero)
2024-12-31 17:21:02.272 T:11482    info <general>: Using Release Kodi x32
2024-12-31 17:21:02.272 T:11482    info <general>: Kodi compiled 2024-12-17 by GCC 10.2.1 for Linux ARM 32-bit version 5.10.158 (330398)
2024-12-31 17:21:02.272 T:11482    info <general>: Running on OSMC Vero V with Open Source Media Center 2024.10-1, kernel: Linux ARM 32-bit version 4.9.269-72-osmc
```

Hope you have a great evening and a happy new year :)

**Comment by Eugeniusz-Gienek** [comment]
@Theetjuh - please check the version 0.0.6.2 - I've merged the changes madr by @Galaxy102

Happy New Year to You guys too!!

**Comment by Theetjuh** [comment]
Works perfectly under OSMC and CE-NG, happy new year and thanks for the quick fix!

**Comment by Eugeniusz-Gienek** [comment]
Awesome! Thanks to @Galaxy102 for quick fix :)
